sudo: false
language: go

go:
  - 1.3
  - 1.4
  - 1.5
  - 1.9

before_install:
  - go get github.com/mattn/goveralls
  - go get github.com/chuckpreslar/emission
  - go get github.com/go-macaron/inject

script: go test -v -cover -race
